### ISSUE TITLE
Proxied messages don't appear in console

### ISSUE THREAD

**Issue by ghost** [HolyAntimony/PluralKitMC#2]
Proxied messages don't show up in the server console

![Screenshot of minecraft chat with the message "this is a normal message" from user Kaytastrophe, followed by a message "this is a proxied message" from member Strawberry](https://user-images.githubusercontent.com/32821049/152918021-ec92d7d9-2e26-4dee-9322-538169e8b6dc.png)
![Screenshot of server console with the message "<Kaytastrophe> this is a normal message" without being followed by the respective proxied message](https://user-images.githubusercontent.com/32821049/152918030-96ced9d3-2408-4ce4-a6c5-c1fa0b9a1f29.png)

Expected behavior:
Something like ```[xx:xx:xx INFO] (Kaytastrophe) <Strawberry> this is a proxied message``` appearing in the console.

**Comment by Allymonies** [comment]
Fixed this issue in v0.4.11 (bdd700c), thanks for the report!

**Comment by Allymonies** [comment]
Will probably add an option, enabled by default, to have the username logged too, which would be helpful for administrative purposes, as you've suggested, but for now I'm just logging what players are shown.
