### ISSUE TITLE
[Request] Adding PlaceholderAPI

### ISSUE THREAD

**Issue by MaikeruP** [HolyAntimony/PluralKitMC#5]
Hello! Love the work being done on this. Would there be any way that I can use placeholders from PlaceholderAPI in message_format in the config? This would make all of the messages similar to the other messages on the server. Thank you so much!!

**Comment by Allymonies** [comment]
Thanks for the suggestion! The new release, 0.4.15 adds support for PlaceholderAPI :) let me know if you run into any issues!
