### ISSUE TITLE
Member unloading bug

### ISSUE THREAD

**Issue by ChromaticRose** [HolyAntimony/PluralKitMC#6]
When playing on Paper 1.19.2, about 5 minutes after setting a system, all members of the system will unload. The system will still be linked to the account, but no proxying will occur and no members will appear when using the find, random, autoproxy or member commands. Using the update command seems to fix the issue. This was able to be recreated in two separate servers.

**Comment by Allymonies** [comment]
Looked into this and it looks like it was a rate limit problem, I've fixed this in version 0.4.15, let me know if you run into any further issues!
